MVS-42 Implement DTO entities (MVS-51 Implement MovieDto)
VikaTamazian/moviestore pull request #27
Opened 2021-11-03 15:52 UTC by AnastasiyaIlkevich

MVS-51 Implement MovieDto

2021-11-08 19:16 UTC, RomanKashenok requested changes
Для каких целей какое dto у тебя используется / планируется использовать ?

2021-11-08 19:16 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/GenreDto.java
> +        genre.setExternalId(genreDto.getId());
почему externalId? 
откуда куда информацию о жанре с помощью этого дто ты передаешь?

2021-11-08 19:16 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/GenresDto.java
> +public class GenresDto {
убирай - не нужная обертка

2021-11-08 19:16 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/MovieDto.java
> +    GenreRepository genreRepository;
никакой логики в ДТО - это класс для обмена данными, а не инъекции в него репозиториев

2021-11-08 19:16 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/ProfileDto.java
> +    private User user;
наверное тут тоже тогда дто?

2021-11-09 19:22 UTC, AnastasiyaIlkevich commented on src/main/java/com/trainee/moviestore/dto/GenreDto.java
> +        genre.setExternalId(genreDto.getId());
Я переименую. Это я получаю с themoviedb все имеющиеся жанры для дальнейшего сохранения в базе данных. Делаю это для того чтоб потом при получении фильма по title (мне приходит подобный json 
"results":[{"adult":false,"backdrop_path":"/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg","genre_ids":[28,878],"id":603,"original_language":"en","original_title":"The Matrix", и т.д.}
То есть жанры я вижу в виде массива чисел. Без name. А после заполнения базы нужно будет только будет сопоставить externalId и подтянуть название. Ну или в будущем логика будет другая, но запонить таблицу жанры всё равно нужно.

2021-11-09 19:36 UTC, AnastasiyaIlkevich commented on src/main/java/com/trainee/moviestore/dto/GenresDto.java
> +public class GenresDto {
убрала (у меня с ней легко получилось распарсить, а без неё пока не знаю как это сделать)

2021-11-09 19:37 UTC, AnastasiyaIlkevich commented on src/main/java/com/trainee/moviestore/dto/MovieDto.java
> +    GenreRepository genreRepository;
убрала

2021-11-18 17:34 UTC, RomanKashenok requested changes

2021-11-18 17:34 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/GenreSaveTmdbDto.java
> +    public GenreSaveTmdbDto fromGenre(Genre genre) {
а мы в каких-нибудь кейсах планируем из жанра у нас в базе составлять жанр для themoviedb?

2021-11-18 17:34 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/MovieSaveTmdbDto.java
> +    public MovieSaveTmdbDto fromUser(Movie movie) {
from User? :) а мы точно хотим перегонять в этом направлении, как и с жанрами?

2021-11-18 17:34 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/MovieUpdateDto.java
> +    public MovieUpdateDto fromMovie(Movie movie) {
тож самое

2021-11-18 17:34 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/MovieUpdateTmdbDto.java
> +public class MovieUpdateTmdbDto {
а для чего это вот будет использоваться?

2021-11-18 17:34 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/UserMovieInfoDto.java
> +    public UserMovie toUserMovie() {
точно надо? Когда буде исаользоваться?

2021-11-18 17:34 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/dto/UserUpdateForAdminDto.java
> +public class UserUpdateForAdminDto {
давай ограничимся одним апдейт дто для юзера

2021-11-21 16:27 UTC, AnastasiyaIlkevich commented on src/main/java/com/trainee/moviestore/dto/GenreSaveTmdbDto.java
> +    public GenreSaveTmdbDto fromGenre(Genre genre) {
Не планируем))

2021-11-21 16:28 UTC, AnastasiyaIlkevich commented on src/main/java/com/trainee/moviestore/dto/MovieSaveTmdbDto.java
> +    public MovieSaveTmdbDto fromUser(Movie movie) {
подловил)))

2021-11-21 16:33 UTC, AnastasiyaIlkevich commented on src/main/java/com/trainee/moviestore/dto/MovieUpdateTmdbDto.java
> +public class MovieUpdateTmdbDto {
MovieUpdateTmdbDto будет использоватся при запросе фильма на themoviedb по externalId для обновления.
а MovieUpdateDto будет использоваться для наших корректоровок фильмов

2021-11-21 16:41 UTC, AnastasiyaIlkevich commented on src/main/java/com/trainee/moviestore/dto/UserMovieInfoDto.java
> +    public UserMovie toUserMovie() {
Эта DTO сщздано для Викиной таски

2021-11-21 16:47 UTC, AnastasiyaIlkevich commented on src/main/java/com/trainee/moviestore/dto/UserUpdateForAdminDto.java
> +public class UserUpdateForAdminDto {
хорошо. Уберу и оставлю одно изменение.

2021-12-06 10:02 UTC, RomanKashenok approved these changes

2021-12-06 10:20 UTC, merged