Mvs 4 implements model classes
VikaTamazian/moviestore pull request #3
Opened 2021-09-21 18:40 UTC by lecterh

Some base model (will be correct after agreement DB's chema)

2021-09-21 19:03 UTC, RomanKashenok requested changes

2021-09-21 19:03 UTC, RomanKashenok commented on .idea/compiler.xml
>    <component name="CompilerConfiguration">
убери директорию .idea и все, которые не относятся к проекту из репозитория и внеси в .gitignore

2021-09-21 19:03 UTC, RomanKashenok commented on build.gradle
> +	compileOnly 'org.projectlombok:lombok:1.18.20'
compile и все производные устарели - замени на актуальный скоуп

2021-09-21 19:03 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/model/Genre.java
> +public class Genre {
@Entity?

2021-09-21 19:03 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/model/Profile.java
> +    @JoinColumn(name = "id")
Уверен, что у профиля должен быть юзер, а не наоборот?

2021-09-21 19:21 UTC, lecterh commented on .idea/compiler.xml
>    <component name="CompilerConfiguration">
Done

2021-09-21 19:44 UTC, lecterh commented on src/main/java/com/trainee/moviestore/model/Genre.java
> +public class Genre {
Я @Entity пока не вставлял, а то пока нету БД и известных @Column(name = ""), ругается

2021-09-30 14:46 UTC, lecterh reviewed
Update basic models

2021-09-30 14:54 UTC, RomanKashenok requested changes

2021-09-30 14:54 UTC, RomanKashenok commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter'
запусти билд с опцией --scan и посмотри нет ли у тебя уже этого стартера

2021-09-30 14:54 UTC, RomanKashenok commented on build.gradle
> +	testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
то же самое

2021-09-30 14:54 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/model/UserMovie.java
> +    private long movieId;
давай определимся ,по movie_id мы будем доставать айдишник или сам фильм? потому как сейчас у тебя и то и то

2021-09-30 14:54 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/model/UserMovie.java
> +    private Statuses status;
Statuses ?

2021-10-05 12:53 UTC, RomanKashenok approved these changes
Там есть неправильные вещи. Я аппрувнул, потому что мало ли ты хочешь больше приключений и страданий в будущем

2021-10-05 12:53 UTC, RomanKashenok commented on src/main/java/com/trainee/moviestore/model/Role.java
> +    private Set<User> users;
У нас центральная фигура - юзер. У юзера есть профиль, а не  у профиля есть юзер!

2021-10-07 15:35 UTC, RomanKashenok approved these changes

2021-10-07 15:41 UTC, merged